name: timezone_finder
description: Finds the time zone name (according to the IANA time zone database) for any position on Earth given by latitude and longitude coordinates in degrees.
version: 0.0.1
homepage: https://github.com/mikljacq/timezone_finder

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  geojson: ^1.0.0
  geopoint: ^1.0.0
  async: ^2.6.1
  sqlite3: ^2.9.0
  archive: ^4.0.7

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
dependency_overrides:
  latlong2: ^0.8.0